export const REVIEW_QUEUE_VISIBLE_COLUMNS = [
  "ds_number",
  "project_title",
  "extracted_business_name",
  "extracted_business_category",
  "status",
  "overall_score",
  "reviewer_notes",
] as const;

export const REVIEW_QUEUE_ALL_COLUMNS = [
  "ds_number",
  "ds_id",
  "project_title",
  "project_type",
  "shop_code",
  "normalized_url",
  "domain",
  "canonical_domain",
  "source_column",
  "first_req_description_excerpt",
  "first_req_note_excerpt",
  "status",
  "elapsed_ms",
  "error_message",
  "extracted_business_name",
  "extracted_business_category",
  "extracted_tagline",
  "extracted_summary",
  "logo_candidate_count",
  "selected_logo_url",
  "pages_inspected",
  "extraction_provider",
  "extraction_model",
  "business_name_score",
  "category_score",
  "logo_score",
  "brief_score",
  "overall_score",
  "reviewer_notes",
  "business_name_similarity_hint",
  "title_business_name_overlap_hint",
] as const;

export type ReviewQueueRow = Record<(typeof REVIEW_QUEUE_ALL_COLUMNS)[number], string>;
